export const AUTH_LOGIN_REQUEST =  'AUTH_LOGIN_REQUEST';
export const AUTH_LOGIN_SUCCESS =  'AUTH_LOGIN_SUCCESS';
export const AUTH_LOGIN_FAILED =  'AUTH_LOGIN_FAILED';

export const AUTH_SIGNUP_REQUEST =  'AUTH_SIGNUP_REQUEST';
export const AUTH_SIGNUP_SUCCESS =  'AUTH_SIGNUP_SUCCESS';
export const AUTH_SIGNUP_FAILED =  'AUTH_SIGNUP_FAILED';

export const GET_PROFILE_REQUEST =  'GET_PROFILE_REQUEST';
export const GET_PROFILE_SUCCESS =  'GET_PROFILE_SUCCESS';
export const GET_PROFILE_FAILED =  'GET_PROFILE_FAILED';

export const AUTH_LOGOUT = 'AUTH_LOGOUT';

export const GET_EVENT_REQUEST =  'GET_EVENT_REQUEST';
export const GET_EVENT_SUCCESS =  'GET_EVENT_SUCCESS';
export const GET_EVENT_FAILED =  'GET_EVENT_FAILED';

export const CREATE_EVENT_REQUEST =  'CREATE_EVENT_REQUEST';
export const CREATE_EVENT_SUCCESS =  'CREATE_EVENT_SUCCESS';
export const CREATE_EVENT_FAILED =  'CREATE_EVENT_FAILED';