export const AUTH_LOGIN_REQUEST =  'AUTH_LOGIN_REQUEST';
export const AUTH_LOGIN_SUCCESS =  'AUTH_LOGIN_SUCCESS';
export const AUTH_LOGIN_FAILED =  'AUTH_LOGIN_FAILED';

export const AUTH_SIGNUP_REQUEST =  'AUTH_SIGNUP_REQUEST';
export const AUTH_SIGNUP_SUCCESS =  'AUTH_SIGNUP_SUCCESS';
export const AUTH_SIGNUP_FAILED =  'AUTH_SIGNUP_FAILED';

export const AUTH_LOGOUT = 'AUTH_LOGOUT';
