export const AUTH_LOGIN_REQUEST =  'AUTH_LOGIN_REQUEST';
export const AUTH_LOGIN_SUCCESS =  'AUTH_LOGIN_SUCCESS';
export const AUTH_LOGIN_FAILED =  'AUTH_LOGIN_FAILED';

export const PASSWORD_RESET_REQUEST =  'PASSWORD_RESET_REQUEST';
export const PASSWORD_RESET_SUCCESS =  'PASSWORD_RESET_SUCCESS';
export const PASSWORD_RESET_FAILED =  'PASSWORD_RESET_FAILED';

export const EMAIL_OTP_REQUEST =  'EMAIL_OTP_REQUEST';
export const EMAIL_OTP_SUCCESS =  'EMAIL_OTP_SUCCESS';
export const EMAIL_OTP_FAILED =  'EMAIL_OTP_FAILED';

export const EMAIL_OTP_VERIFICATION_REQUEST =  'EMAIL_OTP_VERIFICATION_REQUEST';
export const EMAIL_OTP_VERIFICATION_SUCCESS =  'EMAIL_OTP_VERIFICATION_SUCCESS';
export const EMAIL_OTP_VERIFICATION_FAILED =  'EMAIL_OTP_VERIFICATION_FAILED';

export const AUTH_SIGNUP_REQUEST =  'AUTH_SIGNUP_REQUEST';
export const AUTH_SIGNUP_SUCCESS =  'AUTH_SIGNUP_SUCCESS';
export const AUTH_SIGNUP_FAILED =  'AUTH_SIGNUP_FAILED';

export const GET_PROFILE_REQUEST =  'GET_PROFILE_REQUEST';
export const GET_PROFILE_SUCCESS =  'GET_PROFILE_SUCCESS';
export const GET_PROFILE_FAILED =  'GET_PROFILE_FAILED';

export const AUTH_LOGOUT = 'AUTH_LOGOUT';

export const APPROVE_EVENT_PAYMENT_REQUEST =  'APPROVE_EVENT_PAYMENT_REQUEST';
export const APPROVE_EVENT_PAYMENT_SUCCESS =  'APPROVE_EVENT_PAYMENT_SUCCESS';
export const APPROVE_EVENT_PAYMENT_FAILED =  'APPROVE_EVENT_PAYMENT_FAILED';

export const APPROVE_CONTENT_PAYMENT_REQUEST =  'APPROVE_CONTENT_PAYMENT_REQUEST';
export const APPROVE_CONTENT_PAYMENT_SUCCESS =  'APPROVE_CONTENT_PAYMENT_SUCCESS';
export const APPROVE_CONTENT_PAYMENT_FAILED =  'APPROVE_CONTENT_PAYMENT_FAILED';

export const GOOGLE_AUTH_LOGIN_REQUEST =  'GOOGLE_AUTH_LOGIN_REQUEST';
export const GOOGLE_AUTH_LOGIN_SUCCESS =  'GOOGLE_AUTH_LOGIN_SUCCESS';
export const GOOGLE_AUTH_LOGIN_FAILED =  'GOOGLE_AUTH_LOGIN_FAILED';

export const GET_PAYMENT_REQUEST =  'GET_PAYMENT_REQUEST';
export const GET_PAYMENT_SUCCESS =  'GET_PAYMENT_SUCCESS';
export const GET_PAYMENT_FAILED =  'GET_PAYMENT_FAILED';

export const GET_PAYMENT_TRANSACTION_REQUEST =  'GET_PAYMENT_TRANSACTION_REQUEST';
export const GET_PAYMENT_TRANSACTION_SUCCESS =  'GET_PAYMENT_TRANSACTION_SUCCESS';
export const GET_PAYMENT_TRANSACTION_FAILED =  'GET_PAYMENT_TRANSACTION_FAILED';

export const GET_PAYMENT_WITHDRAW_REQUEST =  'GET_PAYMENT_WITHDRAW_REQUEST';
export const GET_PAYMENT_WITHDRAW_SUCCESS =  'GET_PAYMENT_WITHDRAW_SUCCESS';
export const GET_PAYMENT_WITHDRAW_FAILED =  'GET_PAYMENT_WITHDRAW_FAILED';

export const APPROVE_WITHDRAW_REQUEST =  'APPROVE_WITHDRAW_REQUEST';
export const APPROVE_WITHDRAW_SUCCESS =  'APPROVE_WITHDRAW_SUCCESS';
export const APPROVE_WITHDRAW_FAILED =  'APPROVE_WITHDRAW_FAILED';

export const PAYMENT_WITHDRAW_LIST_REQUEST =  'PAYMENT_WITHDRAW_LIST_REQUEST';
export const PAYMENT_WITHDRAW_LIST_SUCCESS =  'PAYMENT_WITHDRAW_LIST_SUCCESS';
export const PAYMENT_WITHDRAW_LIST_FAILED =  'PAYMENT_WITHDRAW_LIST_FAILED';

export const GET_EVENT_REQUEST =  'GET_EVENT_REQUEST';
export const GET_EVENT_SUCCESS =  'GET_EVENT_SUCCESS';
export const GET_EVENT_FAILED =  'GET_EVENT_FAILED';

export const GET_EVENT_BY_ID_REQUEST =  'GET_EVENT_BY_ID_REQUEST';
export const GET_EVENT_BY_ID_SUCCESS =  'GET_EVENT_BY_ID_SUCCESS';
export const GET_EVENT_BY_ID_FAILED =  'GET_EVENT_BY_ID_FAILED';

export const GET_CONTENT_BY_ID_REQUEST =  'GET_CONTENT_BY_ID_REQUEST';
export const GET_CONTENT_BY_ID_SUCCESS =  'GET_CONTENT_BY_ID_SUCCESS';
export const GET_CONTENT_BY_ID_FAILED =  'GET_CONTENT_BY_ID_FAILED';

export const GET_CREATOR_BY_ID_REQUEST =  'GET_CREATOR_BY_ID_REQUEST';
export const GET_CREATOR_BY_ID_SUCCESS =  'GET_CREATOR_BY_ID_SUCCESS';
export const GET_CREATOR_BY_ID_FAILED =  'GET_CREATOR_BY_ID_FAILED';

export const GET_ALL_EVENT_REQUEST =  'GET_ALL_EVENT_REQUEST';
export const GET_ALL_EVENT_SUCCESS =  'GET_ALL_EVENT_SUCCESS';
export const GET_ALL_EVENT_FAILED =  'GET_ALL_EVENT_FAILED';

export const GET_EVENT_APPROVE_REQUEST =  'GET_EVENT_APPROVE_REQUEST';
export const GET_EVENT_APPROVE_SUCCESS =  'GET_EVENT_APPROVE_SUCCESS';
export const GET_EVENT_APPROVE_FAILED =  'GET_EVENT_APPROVE_FAILED';

export const EVENT_APPROVE_REQUEST =  'EVENT_APPROVE_REQUEST';
export const EVENT_APPROVE_SUCCESS =  'EVENT_APPROVE_SUCCESS';
export const EVENT_APPROVE_FAILED =  'EVENT_APPROVE_FAILED';

export const GET_CONTENT_APPROVE_REQUEST =  'GET_CONTENT_APPROVE_REQUEST';
export const GET_CONTENT_APPROVE_SUCCESS =  'GET_CONTENT_APPROVE_SUCCESS';
export const GET_CONTENT_APPROVE_FAILED =  'GET_CONTENT_APPROVE_FAILED';

export const CONTENT_APPROVE_REQUEST =  'CONTENT_APPROVE_REQUEST';
export const CONTENT_APPROVE_SUCCESS =  'CONTENT_APPROVE_SUCCESS';
export const CONTENT_APPROVE_FAILED =  'CONTENT_APPROVE_FAILED';

export const GET_SPONSOR_PROFILE_REQUEST =  'GET_SPONSOR_PROFILE_REQUEST';
export const GET_SPONSOR_PROFILE_SUCCESS =  'GET_SPONSOR_PROFILE_SUCCESS';
export const GET_SPONSOR_PROFILE_FAILED =  'GET_SPONSOR_PROFILE_FAILED';

export const GET_BANK_DETAILS_REQUEST =  'GET_BANK_DETAILS_REQUEST';
export const GET_BANK_DETAILS_SUCCESS =  'GET_BANK_DETAILS_SUCCESS';
export const GET_BANK_DETAILS_FAILED =  'GET_BANK_DETAILS_FAILED';

export const GET_EVENT_PROFILE_REQUEST =  'GET_EVENT_PROFILE_REQUEST';
export const GET_EVENT_PROFILE_SUCCESS =  'GET_EVENT_PROFILE_SUCCESS';
export const GET_EVENT_PROFILE_FAILED =  'GET_EVENT_PROFILE_FAILED';

export const GET_CONTENT_PROFILE_REQUEST =  'GET_CONTENT_PROFILE_REQUEST';
export const GET_CONTENT_PROFILE_SUCCESS =  'GET_CONTENT_PROFILE_SUCCESS';
export const GET_CONTENT_PROFILE_FAILED =  'GET_CONTENT_PROFILE_FAILED';

export const CREATE_SPONSOR_PROFILE_REQUEST =  'CREATE_SPONSOR_PROFILE_REQUEST';
export const CREATE_SPONSOR_PROFILE_SUCCESS =  'CREATE_SPONSOR_PROFILE_SUCCESS';
export const CREATE_SPONSOR_PROFILE_FAILED =  'CREATE_SPONSOR_PROFILE_FAILED';

export const CREATE_BANK_DETAILS_REQUEST =  'CREATE_BANK_DETAILS_REQUEST';
export const CREATE_BANK_DETAILS_SUCCESS =  'CREATE_BANK_DETAILS_SUCCESS';
export const CREATE_BANK_DETAILS_FAILED =  'CREATE_BANK_DETAILS_FAILED';

export const CREATE_EVENT_PROFILE_REQUEST =  'CREATE_EVENT_PROFILE_REQUEST';
export const CREATE_EVENT_PROFILE_SUCCESS =  'CREATE_EVENT_PROFILE_SUCCESS';
export const CREATE_EVENT_PROFILE_FAILED =  'CREATE_EVENT_PROFILE_FAILED';

export const CREATE_CONTENT_PROFILE_REQUEST =  'CREATE_CONTENT_PROFILE_REQUEST';
export const CREATE_CONTENT_PROFILE_SUCCESS =  'CREATE_CONTENT_PROFILE_SUCCESS';
export const CREATE_CONTENT_PROFILE_FAILED =  'CREATE_CONTENT_PROFILE_FAILED';

export const GET_EVENT_CATEGORY_REQUEST =  'GET_EVENT_CATEGORY_REQUEST';
export const GET_EVENT_CATEGORY_SUCCESS =  'GET_EVENT_CATEGORY_SUCCESS';
export const GET_EVENT_CATEGORY_FAILED =  'GET_EVENT_CATEGORY_FAILED';

export const GET_SPONSORED_EVENT_REQUEST =  'GET_SPONSORED_EVENT_REQUEST';
export const GET_SPONSORED_EVENT_SUCCESS =  'GET_SPONSORED_EVENT_SUCCESS';
export const GET_SPONSORED_EVENT_FAILED =  'GET_SPONSORED_EVENT_FAILED';

export const GET_SPONSORED_CONTENT_BY_ID_REQUEST =  'GET_SPONSORED_CONTENT_BY_ID_REQUEST';
export const GET_SPONSORED_CONTENT_BY_ID_SUCCESS =  'GET_SPONSORED_CONTENT_BY_ID_SUCCESS';
export const GET_SPONSORED_CONTENT_BY_ID_FAILED =  'GET_SPONSORED_CONTENT_BY_ID_FAILED';

export const GET_FAVORITE_EVENT_REQUEST =  'GET_FAVORITE_EVENT_REQUEST';
export const GET_FAVORITE_EVENT_SUCCESS =  'GET_FAVORITE_EVENT_SUCCESS';
export const GET_FAVORITE_EVENT_FAILED =  'GET_FAVORITE_EVENT_FAILED';

export const GET_SPONSORED_CONTANT_REQUEST =  'GET_SPONSORED_CONTANT_REQUEST';
export const GET_SPONSORED_CONTANT_SUCCESS =  'GET_SPONSORED_CONTANT_SUCCESS';
export const GET_SPONSORED_CONTANT_FAILED =  'GET_SPONSORED_CONTANT_FAILED';

export const GET_SPONSORED_ITEM_REQUEST =  'GET_SPONSORED_ITEM_REQUEST';
export const GET_SPONSORED_ITEM_SUCCESS =  'GET_SPONSORED_ITEM_SUCCESS';
export const GET_SPONSORED_ITEM_FAILED =  'GET_SPONSORED_ITEM_FAILED';

export const GET_CONTENT_REQUEST =  'GET_CONTENT_REQUEST';
export const GET_CONTENT_SUCCESS =  'GET_CONTENT_SUCCESS';
export const GET_CONTENT_FAILED =  'GET_CONTENT_FAILED';

export const GET_ALL_CREATOR_REQUEST =  'GET_ALL_CREATOR_REQUEST';
export const GET_ALL_CREATOR_SUCCESS =  'GET_ALL_CREATOR_SUCCESS';
export const GET_ALL_CREATOR_FAILED =  'GET_ALL_CREATOR_FAILED';

export const GET_ALL_CONTENT_REQUEST =  'GET_ALL_CONTENT_REQUEST';
export const GET_ALL_CONTENT_SUCCESS =  'GET_ALL_CONTENT_SUCCESS';
export const GET_ALL_CONTENT_FAILED =  'GET_ALL_CONTENT_FAILED';

export const GET_CONTENT_CATEGORY_REQUEST =  'GET_CONTENT_CATEGORY_REQUEST';
export const GET_CONTENT_CATEGORY_SUCCESS =  'GET_CONTENT_CATEGORY_SUCCESS';
export const GET_CONTENT_CATEGORY_FAILED =  'GET_CONTENT_CATEGORY_FAILED';

export const CREATE_EVENT_REQUEST =  'CREATE_EVENT_REQUEST';
export const CREATE_EVENT_SUCCESS =  'CREATE_EVENT_SUCCESS';
export const CREATE_EVENT_FAILED =  'CREATE_EVENT_FAILED';

export const CREATE_SPONSOR_REQUEST =  'CREATE_SPONSOR_REQUEST';
export const CREATE_SPONSOR_SUCCESS =  'CREATE_SPONSOR_SUCCESS';
export const CREATE_SPONSOR_FAILED =  'CREATE_SPONSOR_FAILED';

export const COMPLETE_EVENT_PAYMENT_REQUEST =  'COMPLETE_EVENT_PAYMENT_REQUEST';
export const COMPLETE_EVENT_PAYMENT_SUCCESS =  'COMPLETE_EVENT_PAYMENT_SUCCESS';
export const COMPLETE_EVENT_PAYMENT_FAILED =  'COMPLETE_EVENT_PAYMENT_FAILED';

export const CREATE_SPONSORING_ITEM_REQUEST =  'CREATE_SPONSORING_ITEM_REQUEST';
export const CREATE_SPONSORING_ITEM_SUCCESS =  'CREATE_SPONSORING_ITEM_SUCCESS';
export const CREATE_SPONSORING_ITEM_FAILED =  'CREATE_SPONSORING_ITEM_FAILED';

export const CREATE_FAVORITE_SPONSOR_REQUEST =  'CREATE_FAVORITE_SPONSOR_REQUEST';
export const CREATE_FAVORITE_SPONSOR_SUCCESS =  'CREATE_FAVORITE_SPONSOR_SUCCESS';
export const CREATE_FAVORITE_SPONSOR_FAILED =  'CREATE_FAVORITE_SPONSOR_FAILED';

export const CREATE_SPONSOR_CONTENT_REQUEST =  'CREATE_SPONSOR_CONTENT_REQUEST';
export const CREATE_SPONSOR_CONTENT_SUCCESS =  'CREATE_SPONSOR_CONTENT_SUCCESS';
export const CREATE_SPONSOR_CONTENT_FAILED =  'CREATE_SPONSOR_CONTENT_FAILED';

export const CREATE_CONTENT_REQUEST =  'CREATE_CONTENT_REQUEST';
export const CREATE_CONTENT_SUCCESS =  'CREATE_CONTENT_SUCCESS';
export const CREATE_CONTENT_FAILED =  'CREATE_CONTENT_FAILED';

export const UPDATE_EVENT_REQUEST =  'UPDATE_EVENT_REQUEST';
export const UPDATE_EVENT_SUCCESS =  'UPDATE_EVENT_SUCCESS';
export const UPDATE_EVENT_FAILED =  'UPDATE_EVENT_FAILED';

export const UPDATE_CONTENT_REQUEST =  'UPDATE_CONTENT_REQUEST';
export const UPDATE_CONTENT_SUCCESS =  'UPDATE_CONTENT_SUCCESS';
export const UPDATE_CONTENT_FAILED =  'UPDATE_CONTENT_FAILED';

export const DELETE_EVENT_REQUEST =  'DELETE_EVENT_REQUEST';
export const DELETE_EVENT_SUCCESS =  'DELETE_EVENT_SUCCESS';
export const DELETE_EVENT_FAILED =  'DELETE_EVENT_FAILED';

export const DELETE_CONTENT_REQUEST =  'DELETE_CONTENT_REQUEST';
export const DELETE_CONTENT_SUCCESS =  'DELETE_CONTENT_SUCCESS';
export const DELETE_CONTENT_FAILED =  'DELETE_CONTENT_FAILED';